# Generated by Django 5.1.3 on 2025-01-02 06:15

import GameServer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameServer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='board',
            field=models.JSONField(default=GameServer.models.Game.default_board, help_text='The game board'),
        ),
    ]
